version: '3'

tasks:
  default:
    desc: Build the application
    cmds:
      - task: build

  build:
    desc: Build the genidi binary
    cmds:
      - CGO_CXXFLAGS="-Wno-vla-cxx-extension" go build -o genidi .
    sources:
      - '**/*.go'
    generates:
      - genidi

  run:
    desc: Build and run the application
    deps: [build]
    cmds:
      - ./genidi

  test:
    desc: Run tests
    cmds:
      - CGO_CXXFLAGS="-Wno-vla-cxx-extension" go test -v ./...

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f genidi

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod download
      - go mod tidy

